name: backend-tests

on:
  workflow_call:  # ce workflow est appelable par d'autres workflows

jobs:
  backend_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      # Si tu as besoin d’un .env spécifique en CI :
      # - name: Prepare CI env file
      #   run: cp .env.ci .env

      - name: Run backend test script
        run: |
          chmod +x start_backend.sh
          python tests/backend-testing.py